### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by obama8mynuggets** [Royal-Rebels/Royal-Rebels#290]
hey tri/will/mellie/recipient, im just concerned that im an architect but i have no access to the architect warps like /warp creative or /warp knighttrain and also i am an active member of the colony funtown however my names prefix remains only "architect" and not the funtown prefix, if you could deal with these whenever is convenient that would be awesome! thanks, -obama8mynuggets

**Comment by melliebean** [comment]
I removed you from all the colonies because I wasn't sure which colony you were actually in as you have recently switched between a few. I tried to ask you in game what colony you were in but you must have been afk as I didn't receive an answer. Please resubmit a book to Bribum_ and we will add you asap. As for the architect thing, not all of our architects have access to the creative world yet as most were recruited to build warzones in the survival world before being granted creative access. I apologize if this wasn't explained better. We have had a lot of creative world briefing and although reversible, this is a nuisance and we have had to be more cautious with who we grant privleges to. We do hope that you can understand that.

**Comment by obama8mynuggets** [comment]
yes i understand, thanks for explaining!
