### ISSUE TITLE
Have wiki entry for Showcase Standalone to teach people how to use it.

### ISSUE THREAD

**Issue by triarry** [Royal-Rebels/Royal-Rebels#357]
- Colony Books

**Comment by de1012005** [comment]
while messing around with the showcase i noticed if you just call it /scs display (w/e the name u like as in game item only) for instance /scs display paper, the command works but if you type /scs remove it doesnt and u get endless paper since that's what the display was set as, if you type in /scs abort it aborts the operation yet if you type in /scs remove you keep getting the previous item you currently had (aka dupe bug possibly a exploit), only way to fix this is to break the block you have the sign attached too.
