### ISSUE TITLE
current bugs as of 03/09/2016 (also happy birthday melliebean)

### ISSUE THREAD

**Issue by de1012005** [Royal-Rebels/Royal-Rebels#457]
1. default chat - no colored names etc..
2. mypet broken
3. when you kill a mob it drops the item to the ground like normal but leaves behind the name of the item on the ground
4. cannot /msg anyone anymore now u do /whisper playersname than msg
5. wizardly magic still out of date
6. issue with spawners not working ones that was there by default skeleton spawner - not spawning skelly's - seems fixed to a certain degree
things that do work:
night vision
warping
/home
checking elevators now: they work as far as i can tell

**Comment by triarry** [comment]
Hello!

Chat broke some time late last night and I am hoping the developer will release a fix tonight. I did not know about the MyPet issue so I will check on that as soon as I get on (I am studying for finals) wizardly magic is not quite ready like I thought it was so that will be out tonight or tomorrow. The msg issue is because of the chat issue.

This will all be resolved by the end of the week by brute force, and the wiki will be in a much more complete state by Sunday night.

**Comment by de1012005** [comment]
thankyou for your speedy response so enjoy your day with your girlfriend thats a order from me lol =)

**Comment by triarry** [comment]
Fixed all but chat & magic, & havent tried the spawenr issue yet.
